--[[
	Multi-language locale strings.
	Supported: enUS, frFR, deDE, esES, esMX, ruRU, zhCN, zhTW

	Access:
	  Localization.current.Key         -- raw lookup on the active locale
	  Localization:Get("Key")           -- same
	  MSB_L("Key", ...)                 -- formatted via string.format, with
	                                    -- enUS fallback then key name

	Non-enUS locales fall back to enUS per-key for any key they don't define,
	so partial translations are safe. Conventions:
	- enUS is the source of truth; every key MUST exist there.
	- Placeholder strings use string.format-style %%d/%%s.
--]]

class "CLocalization"
{
    __init = function(self)
        self.locales = {}

        self.locales["enUS"] = {
            -- Spellbook UI
            ShowPassive = "Show passives",
            SearchAbilities = "Search abilities, keywords",
            NoResults = "No results. Try a different search term.|nFor example, '",
            NoPetSpells = "No pet spells available.",
            LevelShort = "Lvl %d",
            AllRanks = "All ranks",
            PetTab = "Pet",
            OtherTab = "Other",
            CompanionsTab = "Companions",
            MountsTab = "Mounts",
            ToysTab = "Toys",
            TrainerHint = "Visit a class trainer in a major city to fetch the FULL list of available spells.",
            UpcomingLabel = "New spells at %d:",
            SpellCounterLearned = "%d/%d learned",
            SpellCounterOnly = "%d learned",
            SpellCounterUnknown = "%d/? learned",
            PetSpellWarning =
            "ModernSpellBook: Warning - Pet spell %s cannot be cast outside the pet action bar. Please drag the spell there.",
            SettingsResetNotice = "Settings reset (DB version %s).",

            -- Slash command chat output
            CmdDisabled = "Disabled. Using vanilla spellbook.",
            CmdEnabled = "Enabled.",
            CmdTalentEnabled = "Custom talent tree enabled",
            CmdTalentDisabled = "Custom talent tree disabled (using vanilla)",
            CmdReset = "Settings reset to defaults. /reload to apply.",
            CmdCaptured = "Captured %d spells from trainer.",
            CmdRescanCleared = "Trainer cache cleared. Visit a trainer to rescan.",
            CmdRescanNone = "No trainer cache to clear.",
            CmdHelpTitle = "ModernSpellBook commands:",
            CmdHelpToggle = "/msb - Toggle between modern and vanilla spellbook",
            CmdHelpTalents = "/msb talents - Toggle between modern and vanilla talent tree",
            CmdHelpReset = "/msb reset - Reset settings to defaults",
            CmdHelpRescan = "/msb rescan - Clear trainer cache",

            -- Settings dropdown (spellbook)
            OptRememberPage = "Remember page",
            OptSpellCounter = "Spell counter",
            OptShowUnlearned = "Show unlearned",
            OptShowUpcoming = "Show upcoming",
            OptContinuationHeaders = "Continuation headers",
            OptHighlights = "Highlights",
            OptFontSize = "Font size",
            OptSpellTextColor = "Spell text color",
            OptSpellIconFrame = "Spell icon frame",
            OptResetPosScale = "Reset position & scale",
            OptLight = "Light",
            OptDark = "Dark",
            OptLearnedGlow = "Learned spells glow",
            OptLearnedBadge = "Learned spells badge",
            OptAvailableGlow = "Available spells glow",
            OptAvailableBadge = "Available spells badge",
            OptFrameSpells = "Spells",
            OptFrameOther = "Other",
            OptFrameUnlearned = "Unlearned",

            -- Talent tree UI
            TalentTitle = "%s Talents",
            TalentBack = "Back",
            TalentPointsSuffix = "%d points",
            TalentPointAvailable = "%s TALENT POINT AVAILABLE",
            NoTalentPointsAvailable = "NO TALENT POINTS AVAILABLE",
            TalentKeyAbilities = "KEY ABILITIES",
            TalentPointsInvested = "%s TALENT POINTS INVESTED",

            -- Talent settings dropdown
            TalentOptGridLines = "Grid lines",
            TalentOptResetPosScale = "Reset position & scale",
            TalentOptVertical = "Vertical",
            TalentOptDiagonal = "Diagonal",
            TalentOptHorizontal = "Horizontal",
            TalentOptColoring = "Coloring",
            TalentOptVisibility = "Visibility",
            TalentOptAlways = "Always",
            TalentOptOnlyUnlocked = "Only unlocked",
            TalentOptNever = "Never",

            -- Tooltip strings
            TooltipRequiresLevel = "Requires Level %d",
            TooltipRequiresTalent = "Requires talent point.",
            TooltipVisitTrainer = "Visit a class trainer to learn.",

            -- Badge text
            BadgeNew = "New",
            BadgeTrain = "Train",

            -- Spec descriptions (Talent tree expanded view)
            SpecDesc_WARRIOR_1 = "The disciplined master of the battlefield. Wielding a massive two-handed weapon, this warrior relies on strict martial training and adaptive combat stances to outmaneuver their opponent. Every swing is deliberate, waiting for the perfect opening to deliver a devastating, precision strike that severely cripples the target's ability to heal and bleeds them out through deep, calculated wounds.",
            SpecDesc_WARRIOR_2 = "A reckless engine of momentum and pure wrath. Abandoning defense for sheer offensive output, this combatant wields twin blades to maximize strikes and keep their blood boiling. Thriving in the thick of melee, they willingly embrace a death wish, sacrificing their own armor and safety to fuel an unrelenting flurry of vicious attacks, overwhelming the enemy before their own vitality runs dry.",
            SpecDesc_WARRIOR_3 = "The iron bulwark holding the front line. Defined by heavy plate, a scarred shield, and absolute defiance, they control the flow of combat through demoralizing roars and bone-crushing shield bashes. They project a massive, threatening presence to keep the enemy's attention fixed entirely on them, weathering earth-shattering blows by bracing themselves behind steel, standing firm so the rest of the group can survive.",
            SpecDesc_PALADIN_1 = "The stalwart anchor of the vanguard. Wearing heavy plate armor while channeling divine light, they possess an unmatched physical resilience among those who mend the wounded. Through rigid devotion and spiritual efficiency, they sustain an endless stream of quick, radiant mending, keeping their allies standing through grueling wars of attrition while projecting unyielding, righteous auras of protection.",
            SpecDesc_PALADIN_2 = "The devoted bastion against the undead and demonic hordes. Relying on searing the very earth beneath their foes' feet and reacting to incoming strikes with radiant barriers, they wear down multiple adversaries through holy retaliation. They are masters of endurance, absorbing physical punishment and reflecting it back as blinding light, turning their own armor into an instrument of absolute attrition.",
            SpecDesc_PALADIN_3 = "The zealous inquisitor. A slow, methodical crusader who relies on heavy two-handed swings and the unpredictable, explosive power of divine judgment. They break their enemies' defenses through holy condemnation, capitalizing on fleeting moments of weakness to deliver crushing, deliberate blows of wrath, punishing those who thought they could outlast the light.",
            SpecDesc_HUNTER_1 = "A bonded survivalist fighting in perfect synchronization with an apex predator. This tracker channels their primal focus entirely into their tamed companion. Through shared instinct and roaring commands, the beast becomes a frenzied, unstoppable force, tearing through flesh and bone while the archer provides covering fire, ensuring any threat is mauled before it can close the distance.",
            SpecDesc_HUNTER_2 = "The patient, lethal sniper. Operating at the absolute limits of physical range, they control the pacing of the skirmish with concussive blasts and disorienting volleys. They meticulously time their bowstring draws, waiting for the perfect moment to unleash a heavy, armor-piercing arrow, delivering calculated bursts of physical damage that drop a target before they even realize they are being hunted.",
            SpecDesc_HUNTER_3 = "The rugged, tactical frontiersman. When the enemy inevitably closes in, they are already prepared. Relying on heightened agility and an arsenal of hidden, explosive traps, they excel at controlling the very earth of the battlefield. They punish melee attackers with debilitating counterattacks and venomous stings, proving that a tracker is just as dangerous in the dense brush as they are from a watchtower.",
            SpecDesc_ROGUE_1 = "The quiet executioner. Relying on potent, lingering venoms and pinpoint strikes to vital organs, this killer waits in the shadows for the singular, perfect opening. By exploiting moments of vulnerability and striking rapidly with twin daggers, they ensure their target's lifeblood evaporates in a lethal, toxic instant, slipping away before the body even hits the ground.",
            SpecDesc_ROGUE_2 = "The pragmatic frontline duelist. Forsaking the shadows for sheer martial prowess, this fighter stands toe-to-toe with their prey. Armed with swords or heavy maces, they maintain a relentless offensive pressure, weaving their blades in a blur of steel. When overwhelmed, they tap into reserves of pure adrenaline, matching multiple opponents blow for blow with blinding attack speed and unmatched parries.",
            SpecDesc_ROGUE_3 = "The unseen manipulator of the battlefield. Dictating exactly when and how a fight begins, they are a phantom in the dark. Utilizing unparalleled camouflage and premeditated tactics, they cripple their target from the first strike, chaining precise, stunning blows that completely lock down the enemy's ability to react. If the odds ever turn against them, they vanish into thin air, resetting the board on their own terms.",
            SpecDesc_PRIEST_1 = "The ascetic channeler of absolute willpower. Rather than merely mending broken flesh, this cleric anticipates incoming trauma, mitigating fatal blows by wrapping their allies in shimmering, unbreakable barriers of pure faith. They bolster the minds and magical reserves of their comrades, acting as a tactical anchor who manages the momentum of the battle and prevents disasters before blood is even spilled.",
            SpecDesc_PRIEST_2 = "The devout conduit of mending miracles. Commanding the most versatile restorative magic in the realm, they weave potent, deep healing with wide-reaching prayers that mend the entire vanguard at once. Deeply attuned to the spiritual plane, they are capable of pulling groups back from the absolute brink of death, offering a transcendent wave of salvation to those whose physical strength has entirely failed.",
            SpecDesc_PRIEST_3 = "The orthodox outcast wielding forbidden magic. Slipping into a dark, ethereal form, they systematically tear apart the minds of their enemies. They layer agonizing, lingering curses and channel void energy to hobble their target's very thoughts. They thrive on suffering, siphoning the fading life force of their adversaries to mend their own allies, turning the enemy's vitality into a weapon of survival.",
            SpecDesc_SHAMAN_1 = "The destructive channeler of the earth and sky. Calling upon the raw, violent forces of nature, they plant carved wards into the soil to anchor their power. They bypass armor entirely with sudden tremors and hurl chaining lightning through enemy ranks. By mastering the volatile elements, they guarantee devastating, localized storms that end skirmishes in a sudden burst of primal fury.",
            SpecDesc_SHAMAN_2 = "The tribal warrior imbued with the fury of the storm. Wielding a heavy, two-handed weapon, they enter the fray trusting in the ancestral spirits to guide their strikes. Every swing carries the potential of a sudden, violent tempest—a magically empowered flurry of extra, blindingly fast attacks capable of executing an opponent in a single, terrifying burst of physical force.",
            SpecDesc_SHAMAN_3 = "The spiritual mender. Calling upon the soothing properties of living water and resilient earth, they sustain the battle lines with ancestral grace. They are unmatched in group stabilization, weaving fluid waves of restorative magic that jump intelligently from one wounded ally to the next. By placing wards of deep renewal, they ensure the group's mental and magical reserves long outlast the enemy's stamina.",
            SpecDesc_MAGE_1 = "The master of raw, unfettered magical essence. Tapping directly into the world's leylines, they sacrifice all efficiency for overwhelming cosmic superiority. By manipulating the very fabric of time and intellect, they can instantly unleash energies of immense destructive force. When their mental reserves run dry, they draw the ambient magic of the air back into their mind, ready to strike again.",
            SpecDesc_MAGE_2 = "The volatile pyromancer. Focused entirely on maximizing sheer, destructive throughput, they weave molten embers and searing blasts to build up terrifying layers of heat. They chain critical, explosive strikes together, leaving deep, burning wounds on the target. It is a dangerous, reckless dance of power, pushing their fiery output to the absolute limit to incinerate the enemy before they can even draw near.",
            SpecDesc_MAGE_3 = "The pragmatic controller of the battlefield. Dictating the pace of every engagement, they rely on chilling magic to slow their charging enemies to a frozen crawl. Shielded by an impenetrable barrier of ice, they lock down groups with localized blizzards and shattering cold, taking advantage of immobilized targets to deliver lethal, piercing strikes. If caught, they encase themselves in solid frost to survive otherwise fatal blows.",
            SpecDesc_WARLOCK_1 = "The harbinger of inevitable decay. Layering their target in dark hexes and vile corruptions, they rely on debilitating, lingering magic to secure victory. Through dark siphoning and soul-draining rituals, they slowly and methodically extract the vitality from their enemy. It is a terrifying war of attrition where the opponent slowly rots away from the inside, unable to halt their own fading strength.",
            SpecDesc_WARLOCK_2 = "The dark summoner. Drawing their power from the chaotic nether, they treat their summoned horrors not just as servants, but as a source of dark survival. Through forbidden bonds, they share physical pain with their abyssal minions, making the spellcaster incredibly difficult to kill. They are entirely willing to sacrifice their own creations at a moment's notice to absorb raw, demonic power into their own veins.",
            SpecDesc_WARLOCK_3 = "The reckless caster of fel-fire. Channeling the chaotic, burning energy of the abyss, they are a dark reflection of traditional spellcasters. They utilize harvested soul fragments to hurl massive, chaotic infernos, executing fleeing enemies with sudden bursts of dark flame. Their magic is highly volatile and destructive, focused on overwhelming, scorching force that leaves nothing behind but cursed ash.",
            SpecDesc_DRUID_1 = "The warden of nature's cosmic equilibrium. Commanding the astral energies of the moon and the blinding wrath of the sun, they take on the heavily armored form of a mystical avian beast. Standing at range, they weave thorny roots and celestial light to weaken targets before calling down heavy, methodical columns of astral fire, punishing interlopers with the raw, untamed power of the night sky.",
            SpecDesc_DRUID_2 = "The primal shapeshifter. Abandoning the incantations of a spellcaster, they adapt perfectly to the physical demands of raw combat. Taking the form of a great jungle cat, they prowl unseen, shredding armor and bleeding targets with precise, ferocious strikes. When the battle requires a vanguard, they shift into a massive, thick-hided bear, generating furious resilience to act as an impenetrable wall of fur and muscle.",
            SpecDesc_DRUID_3 = "The cultivator of wild life. Excelling at sustaining their allies through layered, blooming magic, they create a buffer of constant mending that allows their group to push through heavy, sustained damage. They coax the very flora of the battlefield to wrap around their comrades, and in moments of dire crisis, they instantly breathe the restorative tranquility of the deep forest back into a fallen ally.",

            -- Talent simulation
            SimTitle = "Talent Simulator",
            SimModeLearned = "Learned",
            SimModeSimulated = "Simulated",
            SimModeLabel = "Mode:",
            SimApplyPlan = "Apply Plan",
            SimResetPlan = "Reset Plan",
            SimApplyRunning = "Applying plan...",
            SimApplyConflict = "Learned talents conflict with plan. Please reset talents first.",
            SimApplyNoPoints = "Not enough talent points to apply plan.",
            SimApplyDone = "Plan applied successfully.",
            SimApplyMatched = "Learned talents already match the plan.",
            SimApplyConfirm = "Apply simulated plan to learned talents?",
            SimApplyTimeout = "Failed to learn next talent. Application stopped.",
            SimPlanFull = "Saved plan library is full.",
            UnknownCategory = "Unknown",
            Professions = "Professions",
            SimResetConfirm = "Reset current plan?",
            SimDefaultPlanName = "Plan",
            SimTooltipRank = "Simulated Rank: %d/%d",
            SimTooltipMode = "(Simulation Mode - Left: +1, Right: -1)",
            SimPointsFormat = "%d/%d",
            SimRenamePlan = "Rename Plan",
            SimRenamePrompt = "Enter new plan name:",
            SimEnterSimulation = "Simulator",
            SimPlanLabel = "Plan:",
            SimSavePlan = "Save",
            SimLoadPlan = "Load",
            SimPlanList = "Plans",
            SimToggleMode = "Mode",
            SimSavePrompt = "Enter plan name:",
            SimNoSavedPlans = "(No saved plans)",
            SimDeletePlan = "Delete",
            SimNewPlanName = "Unnamed",
            SimPlanSaved = "Plan saved: %s",
            SimPlanLoaded = "Plan loaded: %s",
            SimPlanDeleted = "Plan deleted: %s",
            SimBranchReset = "Reset this branch",
            SimShare = "Share",
            SimImport = "Import",
            SimExportPrompt = "Copy this string to share your build:",
            SimImportPrompt = "Paste a talent string to import:",
            SimImportSuccess = "Talent build imported.",
            SimImportFailFormat = "Invalid talent string.",
            SimImportFailClass = "This build is for a different class.",
        }

        self.locales["zhCN"] = {
            -- 法术书界面
            ShowPassive = "显示被动技能",
            SearchAbilities = "搜索技能、关键字",
            NoResults = "没有结果。请尝试其他搜索词。|n例如：'",
            NoPetSpells = "没有可用的宠物技能。",
            LevelShort = "%d 级",
            AllRanks = "所有等级",
            PetTab = "宠物",
            OtherTab = "其他",
            CompanionsTab = "小伙伴",
            MountsTab = "坐骑",
            ToysTab = "玩具",
            TrainerHint = "前往主城的职业训练师，可获取完整的可用法术列表。",
            UpcomingLabel = "%d 级新法术：",
            SpellCounterLearned = "已学 %d/%d",
            SpellCounterOnly = "已学 %d",
            SpellCounterUnknown = "已学 %d/?",
            PetSpellWarning = "ModernSpellBook：警告 - 宠物技能 %s 无法在宠物动作条之外施放，请将其拖到宠物动作条上。",
            SettingsResetNotice = "设置已重置（数据库版本 %s）。",

            -- 斜杠命令聊天输出
            CmdDisabled = "已停用。使用原版法术书。",
            CmdEnabled = "已启用。",
            CmdTalentEnabled = "自定义天赋树已启用",
            CmdTalentDisabled = "自定义天赋树已停用（使用原版）",
            CmdReset = "设置已重置为默认值。请 /reload 应用。",
            CmdCaptured = "已从训练师记录 %d 个法术。",
            CmdRescanCleared = "训练师缓存已清除。请访问训练师重新扫描。",
            CmdRescanNone = "没有可清除的训练师缓存。",
            CmdHelpTitle = "ModernSpellBook 命令：",
            CmdHelpToggle = "/msb - 切换现代/原版法术书",
            CmdHelpTalents = "/msb talents - 切换现代/原版天赋树",
            CmdHelpReset = "/msb reset - 重置设置为默认值",
            CmdHelpRescan = "/msb rescan - 清除训练师缓存",

            -- 设置下拉菜单（法术书）
            OptRememberPage = "记住页面",
            OptSpellCounter = "法术计数",
            OptShowUnlearned = "显示未学习",
            OptShowUpcoming = "显示即将到来",
            OptContinuationHeaders = "续接标题",
            OptHighlights = "高亮",
            OptFontSize = "字体大小",
            OptSpellTextColor = "法术文字颜色",
            OptSpellIconFrame = "法术图标边框",
            OptResetPosScale = "重置位置与缩放",
            OptLight = "浅色",
            OptDark = "深色",
            OptLearnedGlow = "已学法术发光",
            OptLearnedBadge = "已学法术标记",
            OptAvailableGlow = "可用法术发光",
            OptAvailableBadge = "可用法术标记",
            OptFrameSpells = "法术",
            OptFrameOther = "其他",
            OptFrameUnlearned = "未学法术",

            -- 天赋树界面
            TalentTitle = "%s 天赋",
            TalentBack = "返回",
            TalentPointsSuffix = "%d 点",
            TalentPointAvailable = "%s 个可用天赋点",
            NoTalentPointsAvailable = "无可用天赋点",
            TalentKeyAbilities = "核心技能",
            TalentPointsInvested = "已投入 %s 个天赋点",

            -- 天赋设置下拉菜单
            TalentOptGridLines = "网格线",
            TalentOptResetPosScale = "重置位置与缩放",
            TalentOptVertical = "竖线",
            TalentOptDiagonal = "斜线",
            TalentOptHorizontal = "横线",
            TalentOptColoring = "着色",
            TalentOptVisibility = "显示",
            TalentOptAlways = "总是",
            TalentOptOnlyUnlocked = "仅已解锁",
            TalentOptNever = "从不",

            -- 工具提示字符串
            TooltipRequiresLevel = "需要等级 %d",
            TooltipRequiresTalent = "需要天赋点。",
            TooltipVisitTrainer = "前往职业训练师学习。",

            -- 徽章文字
            BadgeNew = "新",
            BadgeTrain = "训练",

            -- 专精描述（天赋树展开视图）
            SpecDesc_WARRIOR_1 = "战场上的纪律大师。手持巨型双手武器，依靠严格的武术训练和灵活的战斗姿态来智取对手。每一次挥击都经过深思熟虑，等待完美的时机发动毁灭性的精准打击，严重削弱目标的治疗能力并通过深层创伤使其流血不止。",
            SpecDesc_WARRIOR_2 = "一台不顾一切的怒火引擎。为了纯粹的进攻输出而放弃防御，双手持刃将攻击频率推到极致，让血液始终沸腾。他们甘愿拥抱死亡的渴望，牺牲自身的护甲和安全来维持无情的猛烈攻势，在自己的生命力耗尽之前击溃敌人。",
            SpecDesc_WARRIOR_3 = "坚守前线的钢铁壁垒。厚重的板甲、伤痕累累的盾牌和绝对的不屈意志是他们的标志，通过挫志怒吼和碎骨盾击掌控战斗节奏。他们散发出巨大而威严的存在感，将敌人的注意力牢牢锁定在自己身上，在钢铁之后承受撼天动地的猛击，屹立不倒，为队友争取生存空间。",
            SpecDesc_PALADIN_1 = "先锋部队的坚实支柱。身披重甲的同时引导神圣之光，他们在治疗者中拥有无与伦比的物理韧性。凭借虔诚的信仰和高效的圣能运用，他们维持着源源不断的快速治疗，在残酷的消耗战中让战友屹立不倒，同时散发出坚不可摧的正义防护光环。",
            SpecDesc_PALADIN_2 = "对抗亡灵和恶魔大军的虔诚堡垒。通过灼烧脚下大地并对来袭攻击施以光辉屏障，他们以神圣报复消磨多个敌人。他们是耐久战的大师，吸收物理伤害并将其化为耀眼之光反射回去，将自身的铠甲化为终极消耗战的利器。",
            SpecDesc_PALADIN_3 = "狂热的审判者。一位缓慢而缜密的十字军战士，依靠沉重的双手挥击和不可预测的神圣审判爆发力。他们通过神圣谴责瓦解敌人防线，抓住转瞬即逝的弱点发动粉碎性的蓄力怒击，惩罚那些以为能熬过圣光的人。",
            SpecDesc_HUNTER_1 = "与顶级掠食者完美同步的共生求生者。这位追踪者将全部原始专注力灌注于驯服的伙伴。通过共享的本能和咆哮的指令，野兽化为狂暴不可阻挡的力量，撕裂血肉和骨骼，而射手则提供掩护火力，确保任何威胁在靠近之前就被撕碎。",
            SpecDesc_HUNTER_2 = "耐心致命的狙击手。在物理射程的极限运作，他们用震荡射击和眩晕齐射掌控战斗节奏。他们精心计算每一次拉弓时机，等待完美瞬间释放沉重的穿甲箭，在目标意识到自己正被猎杀之前，以精准的物理伤害爆发将其击倒。",
            SpecDesc_HUNTER_3 = "粗犷而精于战术的边疆猎手。当敌人不可避免地逼近时，他们早已做好准备。依靠超凡的敏捷和隐藏的爆破陷阱，他们擅长掌控战场的每一寸土地。他们用致命的反击和毒刺惩罚近战攻击者，证明猎手在密林中和哨塔上同样致命。",
            SpecDesc_ROGUE_1 = "沉默的处刑人。依靠剧毒的持续性毒药和对要害器官的精准打击，这名杀手在暗影中等待唯一的完美时机。利用破绽一闪的瞬间，双匕首急速出击，确保目标的生命在致命的毒素瞬间蒸发，在尸体倒下之前就已消失在黑暗中。",
            SpecDesc_ROGUE_2 = "务实的前线决斗者。抛弃暗影，追求纯粹的武技，这名战士与猎物正面交锋。手持利剑或重锤，他们维持着无情的进攻压力，刀光如钢铁旋风般交织。当被压制时，他们释放纯粹的肾上腺素，以令人目眩的攻击速度和无与伦比的招架与多名对手硬碰硬。",
            SpecDesc_ROGUE_3 = "战场上的隐形操控者。精确决定战斗何时以何种方式开始，他们是黑暗中的幽灵。利用无与伦比的潜行和深思熟虑的战术，他们从第一击就瘫痪目标，连锁精准的眩晕打击完全封锁敌人的反应能力。当局势逆转时，他们凭空消失，在自己的规则下重置棋局。",
            SpecDesc_PRIEST_1 = "以绝对意志力进行引导的苦修者。这位牧师不仅仅是修复破碎的肉体，而是预判即将到来的创伤，通过为盟友裹上闪耀的、坚不可摧的纯粹信仰屏障来化解致命打击。他们增强同伴的心智和法力储备，充当战术支点，在鲜血尚未流淌之前就阻止灾难发生。",
            SpecDesc_PRIEST_2 = "虔诚的治愈奇迹导管。掌控着王国中最万能的恢复魔法，他们编织强效深层治疗与覆盖全军的广域祈祷。他们与灵界深度共鸣，能够将团队从死亡的绝对边缘拉回，为那些体力已完全耗尽的人提供超越性的救赎之波。",
            SpecDesc_PRIEST_3 = "掌握禁忌魔法的正统异端。融入暗影般的幽灵形态，他们系统性地摧毁敌人的心智。他们叠加痛苦的持续诅咒并引导虚空能量削弱目标的思想。他们在痛苦中茁壮成长，汲取对手消逝的生命力来治愈自己的盟友，将敌人的生机化为生存的武器。",
            SpecDesc_SHAMAN_1 = "天地之间毁灭性的引导者。召唤大自然原始而暴烈的力量，他们在大地中植入雕刻的符文来锚定能量。他们用突如其来的地震完全无视护甲，向敌阵投掷连锁闪电。通过驾驭狂暴的元素，他们确保发动毁灭性的局部风暴，以原始怒火的突然爆发终结战斗。",
            SpecDesc_SHAMAN_2 = "被风暴之怒灌注的部族战士。手持沉重的双手武器，他们相信祖灵会引导每一次挥击而踏入战场。每一击都携带着突然猛烈风暴的潜力——魔法增幅的额外、令人目眩的极速攻击爆发，足以在单次恐怖的力量喷涌中处决对手。",
            SpecDesc_SHAMAN_3 = "灵性的治愈者。召唤活水的抚慰之力和坚韧大地的庇护，他们以祖灵的恩典维持战线。他们在团队稳定方面无人能及，编织流动的恢复魔法波浪，智能地从一名受伤盟友跳转到另一名。通过放置深层重生的图腾，他们确保团队的精神和法力储备远远超越敌人的耐力。",
            SpecDesc_MAGE_1 = "原始无拘魔法本质的大师。直接汲取世界的法力脉络，他们牺牲一切效率来换取压倒性的宇宙优势。通过操纵时间和智慧的织构，他们能瞬间释放具有巨大破坏力的能量。当精神储备耗尽时，他们将空气中的环境魔法重新注入脑海，准备再次出击。",
            SpecDesc_MAGE_2 = "反复无常的火焰术士。完全专注于最大化纯粹的毁灭输出，他们编织熔岩余烬和灼热冲击来积累恐怖的热量层。他们连锁暴击和爆炸性打击，在目标身上留下深层燃烧创伤。这是一场危险而鲁莽的力量之舞，将火力推至绝对极限，在敌人靠近之前将其化为灰烬。",
            SpecDesc_MAGE_3 = "务实的战场控制者。掌控每一场遭遇的节奏，他们依靠冰冷魔法将冲锋的敌人减速至冻结般的蠕动。在坚不可摧的冰之屏障保护下，他们用局部暴风雪和碎裂冰霜锁定敌群，利用被定身的目标发动致命的穿透打击。若被近身，他们将自己封入坚冰以承受原本致命的打击。",
            SpecDesc_WARLOCK_1 = "不可避免腐朽的先兆。在目标身上叠加黑暗诅咒和邪恶腐蚀，他们依靠削弱性的持续魔法来确保胜利。通过黑暗虹吸和灵魂汲取仪式，他们缓慢而有条不紊地从敌人身上榨取生命力。这是一场恐怖的消耗战，对手从内部缓慢腐烂，无法阻止自身力量的消逝。",
            SpecDesc_WARLOCK_2 = "黑暗召唤师。从混沌虚空中汲取力量，他们将召唤出的恐怖存在不仅视为仆从，更视为黑暗生存的源泉。通过禁忌的联结，他们与深渊奴仆分担物理痛苦，使施法者极难被杀死。他们随时准备牺牲自己的造物，将原始的恶魔之力吸收进自己的血脉。",
            SpecDesc_WARLOCK_3 = "莽撞的邪能施法者。引导深渊的混沌燃烧能量，他们是传统施法者的黑暗映射。他们利用收割的灵魂碎片投掷巨大的混沌地狱火，以突然爆发的暗焰处决逃跑的敌人。他们的魔法极度不稳定且具有破坏性，专注于压倒性的灼烧力量，除了被诅咒的灰烬之外什么都不会留下。",
            SpecDesc_DRUID_1 = "自然宇宙平衡的守护者。驾驭月亮的星界能量和太阳的刺目怒火，他们化身为重甲覆体的神秘猛禽。在远程站位，他们编织荆棘根须和天界之光削弱目标，然后降下沉重而有条不紊的星界火柱，以夜空中原始狂野的力量惩罚入侵者。",
            SpecDesc_DRUID_2 = "原始变形者。抛弃施法者的咒语，他们完美适应原始战斗的物理需求。化身为巨豹，他们隐匿潜行，以精准凶猛的撕裂粉碎护甲并使目标流血。当战斗需要先锋时，他们变身为厚皮巨熊，激发狂暴韧性成为血肉与肌肉铸成的不透之墙。",
            SpecDesc_DRUID_3 = "野生生命的培育者。擅长通过层叠绽放的魔法维持盟友，他们创造持续治愈的缓冲区让团队能够承受大量持续伤害。他们引导战场上的植被缠绕同伴，在危急时刻瞬间将深林的恢复宁静吹入倒下的盟友体内。",

            -- 天赋模拟
            SimTitle = "天赋模拟器",
            SimModeLearned = "已学",
            SimModeSimulated = "模拟",
            SimModeLabel = "模式:",
            SimApplyPlan = "应用模拟",
            SimResetPlan = "重置模拟",
            SimApplyRunning = "正在应用模拟天赋...",
            SimApplyConflict = "已学天赋和模拟天赋冲突，请先洗天赋。",
            SimApplyNoPoints = "可用天赋点不足，无法应用当前模拟天赋。",
            SimApplyDone = "模拟天赋已应用完成。",
            SimApplyMatched = "已学天赋已经和模拟天赋一致。",
            SimApplyConfirm = "是否确认将模拟天赋应用到已学天赋中？",
            SimApplyTimeout = "无法学习下一个天赋，已停止应用。",
            SimPlanFull = "已保存的方案数量已达上限。",
            UnknownCategory = "未知",
            Professions = "专业",
            SimResetConfirm = "是否重置当前模拟方案？",
            SimDefaultPlanName = "方案",
            SimTooltipRank = "模拟等级: %d/%d",
            SimTooltipMode = "（模拟模式 - 左键: +1, 右键: -1）",
            SimPointsFormat = "%d/%d",
            SimRenamePlan = "重命名方案",
            SimRenamePrompt = "请输入新方案名称：",
            SimEnterSimulation = "模拟器",
            SimPlanLabel = "方案:",
            SimSavePlan = "保存方案",
            SimLoadPlan = "载入",
            SimPlanList = "方案列表",
            SimToggleMode = "切换模式",
            SimSavePrompt = "请输入方案名称：",
            SimNoSavedPlans = "（暂无已保存方案）",
            SimDeletePlan = "删除",
            SimNewPlanName = "未命名",
            SimPlanSaved = "方案已保存：%s",
            SimPlanLoaded = "方案已载入：%s",
            SimPlanDeleted = "方案已删除：%s",
            SimBranchReset = "重置此天赋分支",
            SimShare = "分享",
            SimImport = "导入",
            SimExportPrompt = "复制此字符串以分享你的天赋方案：",
            SimImportPrompt = "粘贴天赋字符串以导入：",
            SimImportSuccess = "天赋方案已导入。",
            SimImportFailFormat = "无效的天赋字符串。",
            SimImportFailClass = "该方案属于其他职业。",
        }

        -- zhTW uses the same strings as zhCN
        self.locales["zhTW"] = self.locales["zhCN"]

        self.locales["frFR"] = {
            ShowPassive = "Afficher les passifs",
            SearchAbilities = "Rechercher des sorts, mots-clés",
            NoResults = "Aucun résultat. Essayez un autre terme de recherche.|nPar exemple, '",
            NoPetSpells = "Aucun sort de familier disponible.",
            LevelShort = "Niv. %d",
            AllRanks = "Tous les rangs",
            PetTab = "Familier",
            OtherTab = "Autre",
            TrainerHint = "Rendez-vous chez un maître de classe dans une grande ville pour obtenir la liste complète des sorts disponibles.",
            UpcomingLabel = "Nouveaux sorts au niveau %d :",
            SpellCounterLearned = "%d/%d appris",
            SpellCounterOnly = "%d appris",
            SpellCounterUnknown = "%d/? appris",
            PetSpellWarning = "ModernSpellBook : Attention - Le sort de familier %s ne peut pas être lancé en dehors de la barre d'action du familier. Veuillez y glisser le sort.",
            SettingsResetNotice = "Paramètres réinitialisés (version de la BDD %s).",

            CmdDisabled = "Désactivé. Utilisation du grimoire original.",
            CmdEnabled = "Activé.",
            CmdTalentEnabled = "Arbre de talents personnalisé activé",
            CmdTalentDisabled = "Arbre de talents personnalisé désactivé (utilisation de l'original)",
            CmdReset = "Paramètres réinitialisés par défaut. /reload pour appliquer.",
            CmdCaptured = "%d sorts capturés auprès du maître.",
            CmdRescanCleared = "Cache du maître effacé. Rendez-vous chez un maître pour rescanner.",
            CmdRescanNone = "Aucun cache de maître à effacer.",
            CmdHelpTitle = "Commandes ModernSpellBook :",
            CmdHelpToggle = "/msb - Basculer entre le grimoire moderne et l'original",
            CmdHelpTalents = "/msb talents - Basculer entre l'arbre de talents moderne et l'original",
            CmdHelpReset = "/msb reset - Réinitialiser les paramètres par défaut",
            CmdHelpRescan = "/msb rescan - Effacer le cache du maître",

            OptRememberPage = "Retenir la page",
            OptSpellCounter = "Compteur de sorts",
            OptShowUnlearned = "Afficher non appris",
            OptShowUpcoming = "Afficher à venir",
            OptContinuationHeaders = "En-têtes de continuation",
            OptHighlights = "Mise en surbrillance",
            OptFontSize = "Taille de police",
            OptSpellTextColor = "Couleur du texte des sorts",
            OptSpellIconFrame = "Cadre d'icône de sort",
            OptResetPosScale = "Réinitialiser position et échelle",
            OptLight = "Clair",
            OptDark = "Sombre",
            OptLearnedGlow = "Brillance des sorts appris",
            OptLearnedBadge = "Badge des sorts appris",
            OptAvailableGlow = "Brillance des sorts disponibles",
            OptAvailableBadge = "Badge des sorts disponibles",
            OptFrameSpells = "Sorts",
            OptFrameOther = "Autre",
            OptFrameUnlearned = "Non appris",

            TalentTitle = "Talents %s",
            TalentBack = "Retour",
            TalentPointsSuffix = "%d points",
            TalentPointAvailable = "%s POINT DE TALENT DISPONIBLE",
            NoTalentPointsAvailable = "AUCUN POINT DE TALENT DISPONIBLE",
            TalentKeyAbilities = "CAPACITÉS CLÉS",
            TalentPointsInvested = "%s POINTS DE TALENT INVESTIS",

            TalentOptGridLines = "Lignes de grille",
            TalentOptResetPosScale = "Réinitialiser position et échelle",
            TalentOptVertical = "Vertical",
            TalentOptDiagonal = "Diagonal",
            TalentOptHorizontal = "Horizontal",
            TalentOptColoring = "Coloration",
            TalentOptVisibility = "Visibilité",
            TalentOptAlways = "Toujours",
            TalentOptOnlyUnlocked = "Débloqué seulement",
            TalentOptNever = "Jamais",

            TooltipRequiresLevel = "Niveau %d requis",
            TooltipRequiresTalent = "Nécessite un point de talent.",
            TooltipVisitTrainer = "Rendez-vous chez un maître de classe pour apprendre.",

            BadgeNew = "Nouveau",
            BadgeTrain = "Entraîner",
        }

        self.locales["deDE"] = {
            ShowPassive = "Passive anzeigen",
            SearchAbilities = "Fähigkeiten, Schlüsselwörter suchen",
            NoResults = "Keine Ergebnisse. Versuchen Sie es mit einem anderen Suchbegriff.|nZum Beispiel, '",
            NoPetSpells = "Keine Begleiterfähigkeiten verfügbar.",
            LevelShort = "St. %d",
            AllRanks = "Alle Ränge",
            PetTab = "Begleiter",
            OtherTab = "Sonstige",
            TrainerHint = "Besuchen Sie einen Klassenlehrer in einer großen Stadt, um die VOLLSTÄNDIGE Liste verfügbarer Zauber zu erhalten.",
            UpcomingLabel = "Neue Zauber auf Stufe %d:",
            SpellCounterLearned = "%d/%d erlernt",
            SpellCounterOnly = "%d erlernt",
            SpellCounterUnknown = "%d/? erlernt",
            PetSpellWarning = "ModernSpellBook: Warnung - Begleiterzauber %s kann nicht außerhalb der Begleiteraktionsleiste gewirkt werden. Bitte ziehen Sie den Zauber dorthin.",
            SettingsResetNotice = "Einstellungen zurückgesetzt (DB-Version %s).",

            CmdDisabled = "Deaktiviert. Urspründliches Zauberbuch wird verwendet.",
            CmdEnabled = "Aktiviert.",
            CmdTalentEnabled = "Benutzerdefinierter Talentbaum aktiviert",
            CmdTalentDisabled = "Benutzerdefinierter Talentbaum deaktiviert (Original wird verwendet)",
            CmdReset = "Einstellungen auf Standard zurückgesetzt. /reload zum Anwenden.",
            CmdCaptured = "%d Zauber vom Lehrer erfasst.",
            CmdRescanCleared = "Lehrer-Cache gelöscht. Besuchen Sie einen Lehrer zum Neuscannen.",
            CmdRescanNone = "Kein Lehrer-Cache zum Löschen vorhanden.",
            CmdHelpTitle = "ModernSpellBook-Befehle:",
            CmdHelpToggle = "/msb - Zwischen modernem und ursprünglichem Zauberbuch wechseln",
            CmdHelpTalents = "/msb talents - Zwischen modernem und ursprünglichem Talentbaum wechseln",
            CmdHelpReset = "/msb reset - Einstellungen auf Standard zurücksetzen",
            CmdHelpRescan = "/msb rescan - Lehrer-Cache löschen",

            OptRememberPage = "Seite merken",
            OptSpellCounter = "Zauberzähler",
            OptShowUnlearned = "Ungelernte anzeigen",
            OptShowUpcoming = "Bevorstehende anzeigen",
            OptContinuationHeaders = "Fortsetzungsüberschriften",
            OptHighlights = "Hervorhebungen",
            OptFontSize = "Schriftgröße",
            OptSpellTextColor = "Zaubertextfarbe",
            OptSpellIconFrame = "Zaubersymbolrahmen",
            OptResetPosScale = "Position und Skalierung zurücksetzen",
            OptLight = "Hell",
            OptDark = "Dunkel",
            OptLearnedGlow = "Gelernte Zauber leuchten",
            OptLearnedBadge = "Gelernte Zauber Badge",
            OptAvailableGlow = "Verfügbare Zauber leuchten",
            OptAvailableBadge = "Verfügbare Zauber Badge",
            OptFrameSpells = "Zauber",
            OptFrameOther = "Sonstige",
            OptFrameUnlearned = "Ungelernt",

            TalentTitle = "%s Talente",
            TalentBack = "Zurück",
            TalentPointsSuffix = "%d Punkte",
            TalentPointAvailable = "%s TALENTPUNKT VERFÜGBAR",
            NoTalentPointsAvailable = "KEINE TALENTPUNKTE VERFÜGBAR",
            TalentKeyAbilities = "SCHLÜSSELFÄHIGKEITEN",
            TalentPointsInvested = "%s TALENTPUNKTE INVESTIERT",

            TalentOptGridLines = "Gitterlinien",
            TalentOptResetPosScale = "Position und Skalierung zurücksetzen",
            TalentOptVertical = "Vertikal",
            TalentOptDiagonal = "Diagonal",
            TalentOptHorizontal = "Horizontal",
            TalentOptColoring = "Einfärbung",
            TalentOptVisibility = "Sichtbarkeit",
            TalentOptAlways = "Immer",
            TalentOptOnlyUnlocked = "Nur freigeschaltet",
            TalentOptNever = "Nie",

            TooltipRequiresLevel = "Benötigt Stufe %d",
            TooltipRequiresTalent = "Benötigt einen Talentpunkt.",
            TooltipVisitTrainer = "Besuchen Sie einen Klassenlehrer zum Erlernen.",

            BadgeNew = "Neu",
            BadgeTrain = "Lernen",
        }

        self.locales["esES"] = {
            ShowPassive = "Mostrar pasivos",
            SearchAbilities = "Buscar hechizos, palabras clave",
            NoResults = "Sin resultados. Pruebe con un término de búsqueda diferente.|nPor ejemplo, '",
            NoPetSpells = "No hay hechizos de mascota disponibles.",
            LevelShort = "Niv. %d",
            AllRanks = "Todos los rangos",
            PetTab = "Mascota",
            OtherTab = "Otros",
            TrainerHint = "Visita a un instructor de clase en una ciudad capital para obtener la lista COMPLETA de hechizos disponibles.",
            UpcomingLabel = "Nuevos hechizos en nivel %d:",
            SpellCounterLearned = "%d/%d aprendidos",
            SpellCounterOnly = "%d aprendidos",
            SpellCounterUnknown = "%d/? aprendidos",
            PetSpellWarning = "ModernSpellBook: Advertencia - El hechizo de mascota %s no se puede lanzar fuera de la barra de acción de la mascota. Arrastra el hechizo allí.",
            SettingsResetNotice = "Ajustes restablecidos (versión de BD %s).",

            CmdDisabled = "Desactivado. Usando el libro de hechizos original.",
            CmdEnabled = "Activado.",
            CmdTalentEnabled = "Árbol de talentos personalizado activado",
            CmdTalentDisabled = "Árbol de talentos personalizado desactivado (usando el original)",
            CmdReset = "Ajustes restablecidos a valores predeterminados. /reload para aplicar.",
            CmdCaptured = "%d hechizos capturados del instructor.",
            CmdRescanCleared = "Caché del instructor borrada. Visita a un instructor para reescanear.",
            CmdRescanNone = "No hay caché de instructor para borrar.",
            CmdHelpTitle = "Comandos de ModernSpellBook:",
            CmdHelpToggle = "/msb - Alternar entre libro de hechizos moderno y original",
            CmdHelpTalents = "/msb talents - Alternar entre árbol de talentos moderno y original",
            CmdHelpReset = "/msb reset - Restablecer ajustes a valores predeterminados",
            CmdHelpRescan = "/msb rescan - Borrar caché del instructor",

            OptRememberPage = "Recordar página",
            OptSpellCounter = "Contador de hechizos",
            OptShowUnlearned = "Mostrar no aprendidos",
            OptShowUpcoming = "Mostrar próximos",
            OptContinuationHeaders = "Encabezados de continuación",
            OptHighlights = "Resaltados",
            OptFontSize = "Tamaño de fuente",
            OptSpellTextColor = "Color del texto de hechizo",
            OptSpellIconFrame = "Marco de icono de hechizo",
            OptResetPosScale = "Restablecer posición y escala",
            OptLight = "Claro",
            OptDark = "Oscuro",
            OptLearnedGlow = "Brillo de hechizos aprendidos",
            OptLearnedBadge = "Insignia de hechizos aprendidos",
            OptAvailableGlow = "Brillo de hechizos disponibles",
            OptAvailableBadge = "Insignia de hechizos disponibles",
            OptFrameSpells = "Hechizos",
            OptFrameOther = "Otros",
            OptFrameUnlearned = "No aprendidos",

            TalentTitle = "Talentos de %s",
            TalentBack = "Volver",
            TalentPointsSuffix = "%d puntos",
            TalentPointAvailable = "%s PUNTO DE TALENTO DISPONIBLE",
            NoTalentPointsAvailable = "SIN PUNTOS DE TALENTO DISPONIBLES",
            TalentKeyAbilities = "HABILIDADES CLAVE",
            TalentPointsInvested = "%s PUNTOS DE TALENTO INVERTIDOS",

            TalentOptGridLines = "Líneas de cuadrícula",
            TalentOptResetPosScale = "Restablecer posición y escala",
            TalentOptVertical = "Vertical",
            TalentOptDiagonal = "Diagonal",
            TalentOptHorizontal = "Horizontal",
            TalentOptColoring = "Coloreado",
            TalentOptVisibility = "Visibilidad",
            TalentOptAlways = "Siempre",
            TalentOptOnlyUnlocked = "Solo desbloqueados",
            TalentOptNever = "Nunca",

            TooltipRequiresLevel = "Requiere nivel %d",
            TooltipRequiresTalent = "Requiere un punto de talento.",
            TooltipVisitTrainer = "Visita a un instructor de clase para aprender.",

            BadgeNew = "Nuevo",
            BadgeTrain = "Aprender",
        }

        self.locales["esMX"] = {
            ShowPassive = "Mostrar pasivas",
            SearchAbilities = "Buscar habilidades, palabras clave",
            NoResults = "Sin resultados. Intenta con otro término de búsqueda.|nPor ejemplo, '",
            NoPetSpells = "No hay hechizos de mascota disponibles.",
            LevelShort = "Niv. %d",
            AllRanks = "Todos los rangos",
            PetTab = "Mascota",
            OtherTab = "Otros",
            TrainerHint = "Visita a un instructor de clase en una ciudad capital para obtener la lista COMPLETA de hechizos disponibles.",
            UpcomingLabel = "Nuevos hechizos en nivel %d:",
            SpellCounterLearned = "%d/%d aprendidos",
            SpellCounterOnly = "%d aprendidos",
            SpellCounterUnknown = "%d/? aprendidos",
            PetSpellWarning = "ModernSpellBook: Advertencia - El hechizo de mascota %s no se puede lanzar fuera de la barra de acción de la mascota. Arrastra el hechizo ahí.",
            SettingsResetNotice = "Ajustes restablecidos (versión de BD %s).",

            CmdDisabled = "Desactivado. Usando el grimorio original.",
            CmdEnabled = "Activado.",
            CmdTalentEnabled = "Árbol de talentos personalizado activado",
            CmdTalentDisabled = "Árbol de talentos personalizado desactivado (usando el original)",
            CmdReset = "Ajustes restablecidos a valores predeterminados. /reload para aplicar.",
            CmdCaptured = "%d hechizos capturados del instructor.",
            CmdRescanCleared = "Caché del instructor borrada. Visita a un instructor para reescanear.",
            CmdRescanNone = "No hay caché de instructor para borrar.",
            CmdHelpTitle = "Comandos de ModernSpellBook:",
            CmdHelpToggle = "/msb - Alternar entre grimorio moderno y original",
            CmdHelpTalents = "/msb talents - Alternar entre árbol de talentos moderno y original",
            CmdHelpReset = "/msb reset - Restablecer ajustes a valores predeterminados",
            CmdHelpRescan = "/msb rescan - Borrar caché del instructor",

            OptRememberPage = "Recordar página",
            OptSpellCounter = "Contador de hechizos",
            OptShowUnlearned = "Mostrar no aprendidos",
            OptShowUpcoming = "Mostrar próximos",
            OptContinuationHeaders = "Encabezados de continuación",
            OptHighlights = "Resaltados",
            OptFontSize = "Tamaño de fuente",
            OptSpellTextColor = "Color del texto de hechizo",
            OptSpellIconFrame = "Marco de icono de hechizo",
            OptResetPosScale = "Restablecer posición y escala",
            OptLight = "Claro",
            OptDark = "Oscuro",
            OptLearnedGlow = "Brillo de hechizos aprendidos",
            OptLearnedBadge = "Insignia de hechizos aprendidos",
            OptAvailableGlow = "Brillo de hechizos disponibles",
            OptAvailableBadge = "Insignia de hechizos disponibles",
            OptFrameSpells = "Hechizos",
            OptFrameOther = "Otros",
            OptFrameUnlearned = "No aprendidos",

            TalentTitle = "Talentos de %s",
            TalentBack = "Regresar",
            TalentPointsSuffix = "%d puntos",
            TalentPointAvailable = "%s PUNTO DE TALENTO DISPONIBLE",
            NoTalentPointsAvailable = "SIN PUNTOS DE TALENTO DISPONIBLES",
            TalentKeyAbilities = "HABILIDADES CLAVE",
            TalentPointsInvested = "%s PUNTOS DE TALENTO INVERTIDOS",

            TalentOptGridLines = "Líneas de cuadrícula",
            TalentOptResetPosScale = "Restablecer posición y escala",
            TalentOptVertical = "Vertical",
            TalentOptDiagonal = "Diagonal",
            TalentOptHorizontal = "Horizontal",
            TalentOptColoring = "Coloreado",
            TalentOptVisibility = "Visibilidad",
            TalentOptAlways = "Siempre",
            TalentOptOnlyUnlocked = "Solo desbloqueados",
            TalentOptNever = "Nunca",

            TooltipRequiresLevel = "Requiere nivel %d",
            TooltipRequiresTalent = "Requiere un punto de talento.",
            TooltipVisitTrainer = "Visita a un instructor de clase para aprender.",

            BadgeNew = "Nuevo",
            BadgeTrain = "Aprender",
        }

        self.locales["ruRU"] = {
            ShowPassive = "Показать пассивные",
            SearchAbilities = "Поиск заклинаний, ключевые слова",
            NoResults = "Нет результатов. Попробуйте другой поисковый запрос.|nНапример, '",
            NoPetSpells = "Нет доступных заклинаний питомца.",
            LevelShort = "Ур. %d",
            AllRanks = "Все ранги",
            PetTab = "Питомец",
            OtherTab = "Другое",
            TrainerHint = "Посетите классового тренера в столице, чтобы получить ПОЛНЫЙ список доступных заклинаний.",
            UpcomingLabel = "Новые заклинания на %d уровне:",
            SpellCounterLearned = "Изучено: %d/%d",
            SpellCounterOnly = "Изучено: %d",
            SpellCounterUnknown = "Изучено: %d/?",
            PetSpellWarning = "ModernSpellBook: Внимание - Заклинание питомца %s нельзя применить вне панели действий питомца. Перетащите заклинание туда.",
            SettingsResetNotice = "Настройки сброшены (версия БД %s).",

            CmdDisabled = "Отключено. Используется стандартный справочник заклинаний.",
            CmdEnabled = "Включено.",
            CmdTalentEnabled = "Пользовательское дерево талантов включено",
            CmdTalentDisabled = "Пользовательское дерево талантов отключено (используется стандартное)",
            CmdReset = "Настройки сброшены. /reload для применения.",
            CmdCaptured = "Получено %d заклинаний от тренера.",
            CmdRescanCleared = "Кеш тренера очищен. Посетите тренера для повторного сканирования.",
            CmdRescanNone = "Нет кеша тренера для очистки.",
            CmdHelpTitle = "Команды ModernSpellBook:",
            CmdHelpToggle = "/msb - Переключение между современным и стандартным справочником",
            CmdHelpTalents = "/msb talents - Переключение между современным и стандартным деревом талантов",
            CmdHelpReset = "/msb reset - Сброс настроек",
            CmdHelpRescan = "/msb rescan - Очистить кеш тренера",

            OptRememberPage = "Запоминать страницу",
            OptSpellCounter = "Счётчик заклинаний",
            OptShowUnlearned = "Показать неизученные",
            OptShowUpcoming = "Показать предстоящие",
            OptContinuationHeaders = "Заголовки продолжения",
            OptHighlights = "Подсветка",
            OptFontSize = "Размер шрифта",
            OptSpellTextColor = "Цвет текста заклинаний",
            OptSpellIconFrame = "Рамка иконки заклинания",
            OptResetPosScale = "Сбросить позицию и масштаб",
            OptLight = "Светлый",
            OptDark = "Тёмный",
            OptLearnedGlow = "Свечение изученных заклинаний",
            OptLearnedBadge = "Значок изученных заклинаний",
            OptAvailableGlow = "Свечение доступных заклинаний",
            OptAvailableBadge = "Значок доступных заклинаний",
            OptFrameSpells = "Заклинания",
            OptFrameOther = "Другое",
            OptFrameUnlearned = "Неизученные",

            TalentTitle = "Таланты: %s",
            TalentBack = "Назад",
            TalentPointsSuffix = "%d очков",
            TalentPointAvailable = "%s ОЧКО ТАЛАНТОВ ДОСТУПНО",
            NoTalentPointsAvailable = "НЕТ ДОСТУПНЫХ ОЧКОВ ТАЛАНТОВ",
            TalentKeyAbilities = "КЛЮЧЕВЫЕ СПОСОБНОСТИ",
            TalentPointsInvested = "ВЛОЖЕНО %s ОЧКОВ ТАЛАНТОВ",

            TalentOptGridLines = "Линии сетки",
            TalentOptResetPosScale = "Сбросить позицию и масштаб",
            TalentOptVertical = "Вертикальные",
            TalentOptDiagonal = "Диагональные",
            TalentOptHorizontal = "Горизонтальные",
            TalentOptColoring = "Окрашивание",
            TalentOptVisibility = "Видимость",
            TalentOptAlways = "Всегда",
            TalentOptOnlyUnlocked = "Только разблокированные",
            TalentOptNever = "Никогда",

            TooltipRequiresLevel = "Требуется уровень %d",
            TooltipRequiresTalent = "Требуется очко таланта.",
            TooltipVisitTrainer = "Посетите классового тренера для изучения.",

            BadgeNew = "Новое",
            BadgeTrain = "Обучение",
        }

        self.current = self.locales[GetLocale()] or self.locales["enUS"]
        -- Guarantee every key exists on current (fall back to enUS for missing keys)
        local enUS = self.locales["enUS"]
        if (self.current ~= enUS) then
            for key, value in pairs(enUS) do
                if (self.current[key] == nil) then
                    self.current[key] = value
                end
            end
        end
    end,

    Get = function(self, key)
        return self.current[key] or self.locales["enUS"][key] or key
    end,
}

Localization = CLocalization()

-- Formatted lookup helper: MSB_L("UpcomingLabel", level)
-- Uses string.format-style placeholders in the locale string.
function MSB_L(key, ...)
    local str = Localization.current[key] or Localization.locales["enUS"][key] or key
    -- Lua 5.0: use the `arg` table for varargs (no `select` in RpLua 5.0).
    if (table.getn(arg) > 0) then
        return string.format(str, unpack(arg))
    end
    return str
end
